let state={data:null,range:30,rank:'top',editing:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n||0);
const num=n=>new Intl.NumberFormat('ja-JP').format(n||0);
const pct=n=>`${((n||0)*100).toFixed(1)}%`;
async function api(path,options){const r=await fetch(path,{headers:{'content-type':'application/json'},...options});const json=await r.json();if(!r.ok)throw new Error(json.error);return json}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show ${error?'error':''}`;setTimeout(()=>el.className='toast',2600)}
function icon(name){return {impressions:'◉',engagement_rate:'♡',follows:'↗',link_clicks:'↗',conversions:'✓'}[name]||'·'}
async function load(){state.data=await api(`/api/dashboard?range=${state.range}`);render()}
function render(){const d=state.data;$('#revenue').textContent=money(d.totals.revenue);$('#queueCount').textContent=d.approvalQueue.length;$('#updated').textContent=new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});$('#bars').innerHTML=[28,38,31,48,44,60,55,75,67,88,82,100].map((h,i)=>`<i style="height:${h}%" class="${i>8?'hot':''}"></i>`).join('');renderQueue();renderMetrics();renderRanking();renderInsights()}
function renderQueue(){const cards=state.data.approvalQueue;$('#approvalQueue').innerHTML=cards.length?cards.map((p,i)=>`<article class="post-card"><div class="post-meta"><span class="variant">${p.variant}</span><div><b>${p.theme}</b><small>${p.content_type.replace('_',' ')} · ${p.hook_type}</small></div><span class="score">${p.review_score}<small>/90</small></span></div><p class="post-copy">${p.content.replaceAll('\n','<br>')}</p><div class="review-note"><span>✦</span><p><b>AI REVIEW</b>${p.review_notes}</p></div><div class="card-actions"><button class="btn reject" data-reject="${p.post_id}">却下</button><button class="btn ghost" data-edit="${p.post_id}">編集</button><button class="btn primary" data-approve="${p.post_id}">承認する <span>→</span></button></div></article>`).join(''):`<div class="empty"><b>すべて確認済みです</b><span>新しい投稿候補はありません。</span></div>`;bindActions()}
function renderMetrics(){const t=state.data.totals;const items=[['impressions','インプレッション',num(t.impressions),'+12.8%'],['engagement_rate','エンゲージメント率',pct(t.engagement_rate),'+1.2pt'],['follows','新規フォロワー',num(t.follows),'+8.4%'],['link_clicks','リンククリック',num(t.link_clicks),'+24.1%'],['conversions','コンバージョン',num(t.conversions),'+3']];$('#metrics').innerHTML=items.map(([k,l,v,c])=>`<article><span class="metric-icon">${icon(k)}</span><small>${l}</small><strong>${v}</strong><em>${c}</em></article>`).join('')}
function renderRanking(){const list=state.rank==='top'?state.data.topPosts:state.data.worstPosts;$('#ranking').innerHTML=list.map((p,i)=>`<div class="rank-row"><span class="rank">0${i+1}</span><p>${p.content.slice(0,46)}${p.content.length>46?'…':''}<small>${p.theme} · ${new Date(p.posted_at).toLocaleDateString('ja-JP',{month:'short',day:'numeric'})}</small></p><div><b>${num(p.impressions)}</b><small>IMP</small></div><div><b>${pct(p.engagement_rate)}</b><small>ER</small></div><div><b>${money(p.revenue)}</b><small>売上</small></div></div>`).join('')}
function renderInsights(){const list=state.data.insights;$('#insights').innerHTML=list.slice(0,3).map((x,i)=>`<article class="insight"><span>${['01','02','03'][i]}</span><div><h3>${x.title}</h3><p>${x.data_text}</p><div class="action"><b>NEXT</b>${x.action}</div><small>source: ${x.source} · n=${x.sample_size} · ${x.period} · <em class="confidence ${x.confidence}">${x.confidence}</em></small></div></article>`).join('')}
function bindActions(){$$('[data-approve]').forEach(b=>b.onclick=()=>status(b.dataset.approve,'approved','承認しました'));$$('[data-reject]').forEach(b=>b.onclick=()=>status(b.dataset.reject,'rejected','却下しました'));$$('[data-edit]').forEach(b=>b.onclick=()=>{state.editing=Number(b.dataset.edit);const p=state.data.approvalQueue.find(x=>x.post_id===state.editing);$('#editContent').value=p.content;$('#charCount').textContent=p.content.length;$('#editDialog').showModal()})}
async function status(id,status,msg){try{await api(`/api/posts/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast(msg);await load()}catch(e){toast(e.message,true)}}
$('#editContent').oninput=e=>$('#charCount').textContent=e.target.value.length;
$('#saveEdit').onclick=async()=>{try{await api(`/api/posts/${state.editing}`,{method:'PATCH',body:JSON.stringify({content:$('#editContent').value})});$('#editDialog').close();toast('投稿を更新しました');await load()}catch(e){toast(e.message,true)}};
$$('[data-range]').forEach(b=>b.onclick=()=>{$$('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.range=Number(b.dataset.range);load()});
$$('[data-rank]').forEach(b=>b.onclick=()=>{$$('[data-rank]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.rank=b.dataset.rank;renderRanking()});
$('#reviewAll').onclick=()=>$('#approvalQueue').scrollIntoView({behavior:'smooth'});
load().catch(e=>toast(e.message,true));
